from __future__ import annotations

import hashlib
from importlib.machinery import SourceFileLoader
import importlib.util
import json
import os
from pathlib import Path
import shutil
import stat
import subprocess

import pytest


ROOT = Path(__file__).resolve().parents[2]
DEPLOY = ROOT / "deploy/gas-city"
PREPARE = DEPLOY / "bin/prepare-worker-boundary"
SUPERVISOR = DEPLOY / "docker/provider-supervisor.py"


def _load_extensionless(name: str, path: Path):
    loader = SourceFileLoader(name, str(path))
    spec = importlib.util.spec_from_loader(name, loader)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


def _load_supervisor():
    spec = importlib.util.spec_from_file_location("cross_rig_supervisor_test", SUPERVISOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _private(path: Path) -> Path:
    path.mkdir(parents=True, exist_ok=True)
    path.chmod(0o700)
    return path


def _write(path: Path, content: bytes | str, mode: int = 0o600) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, str):
        path.write_text(content, encoding="utf-8")
    else:
        path.write_bytes(content)
    path.chmod(mode)
    return path


def _boundary_fixture(tmp_path: Path) -> dict[str, Path]:
    city = _private(tmp_path / "gas-city")
    hq_beads = _private(city / ".beads")
    rig = _private(tmp_path / "aegis")
    aegis_beads = _private(rig / ".beads")
    output = _private(tmp_path / "boundary")
    host_city = city / "host-city.toml"
    worker_city = city / "worker-city.toml"
    shutil.copyfile(DEPLOY / "config/city.toml", host_city)
    shutil.copyfile(DEPLOY / "config/city.worker.toml", worker_city)
    host_city.chmod(0o600)
    worker_city.chmod(0o600)
    hq_config = _write(
        hq_beads / "config.yaml",
        "issue_prefix: gc\n"
        "dolt.auto-start: false\n"
        "gc.endpoint_origin: managed_city\n"
        "gc.endpoint_status: verified\n",
    )
    aegis_config = _write(
        aegis_beads / "config.yaml",
        "# generated by bd init\n# credentials are launcher-owned\n",
    )
    metadata = _write(
        aegis_beads / "metadata.json",
        json.dumps(
            {
                "backend": "dolt",
                "database": "dolt",
                "dolt_database": "aegis_beads",
                "dolt_mode": "server",
                "dolt_server_host": "127.0.0.1",
                "dolt_server_port": 33071,
                "dolt_server_user": "aegis_beads",
                "project_id": "74eb5b48-1390-4fc8-a88d-2b979bcfa7b5",
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
    )
    return {
        "city": city,
        "rig": rig,
        "output": output,
        "host_city": host_city,
        "worker_city": worker_city,
        "hq_config": hq_config,
        "aegis_config": aegis_config,
        "metadata": metadata,
    }


def _prepare(module, fixture: dict[str, Path], role: str) -> int:
    arguments = [
        "--role",
        role,
        "--host-city",
        str(fixture["host_city"]),
        "--worker-city",
        str(fixture["worker_city"]),
        "--output-dir",
        str(fixture["output"]),
    ]
    if role in {"hq", "mayor"}:
        arguments.extend(("--hq-beads-config", str(fixture["hq_config"])))
    if role in {"aegis", "mayor"}:
        arguments.extend(
            (
                "--aegis-beads-config",
                str(fixture["aegis_config"]),
                "--aegis-metadata",
                str(fixture["metadata"]),
            )
        )
    return module.main(arguments)


def test_prepare_mayor_boundary_is_exact_private_and_idempotent(tmp_path: Path) -> None:
    module = _load_extensionless("prepare_worker_boundary_test", PREPARE)
    fixture = _boundary_fixture(tmp_path)

    assert _prepare(module, fixture, "mayor") == 0
    assert _prepare(module, fixture, "mayor") == 0

    output = fixture["output"]
    assert {path.name for path in output.iterdir()} == {
        "aegis-config.yaml",
        "aegis-metadata.json",
        "host-city.toml",
        "hq-config.yaml",
        "worker-boundary.json",
    }
    assert all(
        stat.S_IMODE(path.stat().st_mode) == 0o600 and path.stat().st_nlink == 1
        for path in output.iterdir()
    )
    assert (output / "host-city.toml").read_bytes() == fixture["host_city"].read_bytes()
    assert (output / "hq-config.yaml").read_bytes() == module.HQ_CONFIG_OVERLAY
    assert (output / "aegis-config.yaml").read_bytes() == module.AEGIS_CONFIG_OVERLAY
    projected = json.loads((output / "aegis-metadata.json").read_text())
    assert projected["dolt_server_host"] == "gas-city-aegis-dolt"
    assert projected["dolt_server_port"] == 3306
    assert projected["project_id"] == "74eb5b48-1390-4fc8-a88d-2b979bcfa7b5"
    receipt = json.loads((output / "worker-boundary.json").read_text())
    assert receipt["role"] == "mayor"
    assert receipt["host_city_sha256"] == hashlib.sha256(
        fixture["host_city"].read_bytes()
    ).hexdigest()
    assert receipt["aegis_metadata_projected_sha256"] == hashlib.sha256(
        (output / "aegis-metadata.json").read_bytes()
    ).hexdigest()


@pytest.mark.parametrize("role", ["hq", "aegis"])
def test_prepare_gives_each_non_mayor_only_its_scope(tmp_path: Path, role: str) -> None:
    module = _load_extensionless(f"prepare_worker_boundary_{role}_test", PREPARE)
    fixture = _boundary_fixture(tmp_path)

    assert _prepare(module, fixture, role) == 0
    names = {path.name for path in fixture["output"].iterdir()}
    if role == "hq":
        assert names == {"host-city.toml", "hq-config.yaml", "worker-boundary.json"}
    else:
        assert names == {
            "aegis-config.yaml",
            "aegis-metadata.json",
            "host-city.toml",
            "worker-boundary.json",
        }


def test_prepare_rejects_non_endpoint_city_drift_and_retained_secret(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    module = _load_extensionless("prepare_worker_boundary_reject_test", PREPARE)
    fixture = _boundary_fixture(tmp_path)
    worker = fixture["worker_city"]
    worker.write_text(
        worker.read_text().replace("max_active_sessions = 4", "max_active_sessions = 5"),
        encoding="utf-8",
    )
    worker.chmod(0o600)
    assert _prepare(module, fixture, "mayor") == 66
    assert "outside endpoints" in capsys.readouterr().err

    shutil.copyfile(DEPLOY / "config/city.worker.toml", worker)
    worker.chmod(0o600)
    retained = fixture["metadata"].parent / ".env"
    _write(retained, "BEADS_DOLT_PASSWORD=must-not-persist\n")
    assert _prepare(module, fixture, "mayor") == 66
    assert ".beads/.env" in capsys.readouterr().err


def test_prepare_rejects_duplicate_or_aliased_aegis_metadata(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    module = _load_extensionless("prepare_worker_boundary_metadata_test", PREPARE)
    fixture = _boundary_fixture(tmp_path)
    metadata = fixture["metadata"]
    metadata.write_text(
        '{"backend":"dolt","backend":"dolt","database":"dolt"}\n',
        encoding="utf-8",
    )
    metadata.chmod(0o600)
    assert _prepare(module, fixture, "aegis") == 66
    assert "duplicate key" in capsys.readouterr().err

    metadata.unlink()
    metadata.symlink_to("config.yaml")
    assert _prepare(module, fixture, "aegis") == 66
    assert "non-symlink" in capsys.readouterr().err


def _secret(path: Path, value: str) -> Path:
    _write(path, value + "\n", 0o600)
    return path


@pytest.mark.parametrize(
    ("role", "sections"),
    [
        ("hq", ["gas-city-hq-dolt:3306"]),
        ("aegis", ["gas-city-aegis-dolt:3306"]),
        ("mayor", ["gas-city-hq-dolt:3306", "gas-city-aegis-dolt:3306"]),
    ],
)
def test_supervisor_materializes_only_role_scoped_credentials_in_tmpfs(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    role: str,
    sections: list[str],
) -> None:
    module = _load_supervisor()
    home = _private(tmp_path / "worker-home")
    primary = _secret(tmp_path / "primary", "H" * 40)
    aegis = _secret(tmp_path / "aegis", "A" * 40)
    credentials = home / ".config/beads/credentials"
    monkeypatch.setattr(module, "WORKER_HOME_PATH", home)
    monkeypatch.setattr(module, "PASSWORD_SECRET_PATH", primary)
    monkeypatch.setattr(module, "AEGIS_PASSWORD_SECRET_PATH", aegis)
    monkeypatch.setattr(module, "DOLT_CREDENTIALS_PATH", credentials)
    monkeypatch.setattr(module, "_exact_mount_type", lambda path: "tmpfs" if path == home else None)
    scoped_user = "aegis_beads" if role == "aegis" else "gas_city_hq"
    scoped_database = "aegis_beads" if role == "aegis" else "hq"
    monkeypatch.setenv("GC_DOLT_USER", scoped_user)
    monkeypatch.setenv("GC_DOLT_DATABASE", scoped_database)
    monkeypatch.setenv("GC_DOLT_PASSWORD", "must-disappear")
    monkeypatch.setenv("BEADS_DOLT_PASSWORD", "must-disappear")
    monkeypatch.setenv("BEADS_DOLT_SERVER_DATABASE", scoped_database)

    assert module.prepare_dolt_credentials(role) == credentials
    content = credentials.read_text(encoding="utf-8")
    assert [line[1:-1] for line in content.splitlines() if line.startswith("[")] == sections
    assert stat.S_IMODE(credentials.stat().st_mode) == 0o600
    assert os.environ["BEADS_CREDENTIALS_FILE"] == str(credentials)
    if role == "mayor":
        assert "GC_DOLT_USER" not in os.environ
        assert "GC_DOLT_DATABASE" not in os.environ
        assert "BEADS_DOLT_SERVER_DATABASE" not in os.environ
    else:
        assert os.environ["GC_DOLT_USER"] == scoped_user
        assert os.environ["GC_DOLT_DATABASE"] == scoped_database
        assert os.environ["BEADS_DOLT_SERVER_DATABASE"] == scoped_database
    assert "GC_DOLT_PASSWORD" not in os.environ
    assert "BEADS_DOLT_PASSWORD" not in os.environ


def test_supervisor_rejects_reused_cross_scope_secret(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    module = _load_supervisor()
    home = _private(tmp_path / "worker-home")
    primary = _secret(tmp_path / "primary", "S" * 40)
    secondary = _secret(tmp_path / "secondary", "S" * 40)
    monkeypatch.setattr(module, "WORKER_HOME_PATH", home)
    monkeypatch.setattr(module, "PASSWORD_SECRET_PATH", primary)
    monkeypatch.setattr(module, "AEGIS_PASSWORD_SECRET_PATH", secondary)
    monkeypatch.setattr(module, "DOLT_CREDENTIALS_PATH", home / ".config/beads/credentials")
    monkeypatch.setattr(module, "_exact_mount_type", lambda _path: "tmpfs")

    with pytest.raises(RuntimeError, match="must be distinct"):
        module.prepare_dolt_credentials("mayor")


def test_supervisor_validates_mayor_worker_and_nested_scope_overlays(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    prepare = _load_extensionless("prepare_worker_boundary_supervisor_test", PREPARE)
    module = _load_supervisor()
    fixture = _boundary_fixture(tmp_path)
    assert _prepare(prepare, fixture, "mayor") == 0

    city = fixture["city"]
    rig = fixture["rig"]
    shutil.copyfile(fixture["worker_city"], city / "city.toml")
    (city / "city.toml").chmod(0o600)
    shutil.copyfile(fixture["output"] / "hq-config.yaml", city / ".beads/config.yaml")
    (city / ".beads/config.yaml").chmod(0o600)
    shutil.copyfile(fixture["output"] / "aegis-config.yaml", rig / ".beads/config.yaml")
    shutil.copyfile(fixture["output"] / "aegis-metadata.json", rig / ".beads/metadata.json")
    (rig / ".beads/config.yaml").chmod(0o600)
    (rig / ".beads/metadata.json").chmod(0o600)
    workdir = _private(city / ".gc/agents/mayor/work")
    image_worker = _write(tmp_path / "image/city.worker.toml", fixture["worker_city"].read_bytes(), 0o444)

    monkeypatch.setattr(module, "IMAGE_ROOT_UID", os.getuid())
    monkeypatch.setattr(module, "IMAGE_WORKER_CITY_CONFIG_PATH", image_worker)
    monkeypatch.setattr(module, "HOST_CITY_CONFIG_PATH", fixture["output"] / "host-city.toml")
    monkeypatch.setattr(module, "HQ_CONFIG_OVERLAY_PATH", fixture["output"] / "hq-config.yaml")
    monkeypatch.setattr(module, "AEGIS_CONFIG_OVERLAY_PATH", fixture["output"] / "aegis-config.yaml")
    monkeypatch.setattr(module, "AEGIS_METADATA_OVERLAY_PATH", fixture["output"] / "aegis-metadata.json")
    monkeypatch.setattr(module, "WORKER_BOUNDARY_RECEIPT_PATH", fixture["output"] / "worker-boundary.json")
    identity = dict(module.AEGIS_RUNTIME_IDENTITY)
    identity["GC_RIG_ROOT"] = str(rig)
    monkeypatch.setattr(module, "AEGIS_RUNTIME_IDENTITY", identity)
    environment = {
        "GC_CITY_ROOT": str(city),
        "GC_WORKER_BOUNDARY_ROLE": "mayor",
        "GC_AGENT": "gastown.mayor",
        "GC_ALIAS": "gastown.mayor",
        "GC_TEMPLATE": "gastown.mayor",
        "GC_SESSION_ORIGIN": "named",
        "GC_HOST_CITY_CONFIG": str(module.HOST_CITY_CONFIG_PATH),
        "GC_IMAGE_WORKER_CITY_CONFIG": str(module.IMAGE_WORKER_CITY_CONFIG_PATH),
        "GC_HQ_CONFIG_OVERLAY": str(module.HQ_CONFIG_OVERLAY_PATH),
        "GC_AEGIS_CONFIG_OVERLAY": str(module.AEGIS_CONFIG_OVERLAY_PATH),
        "GC_AEGIS_METADATA_OVERLAY": str(module.AEGIS_METADATA_OVERLAY_PATH),
    }
    for key, value in environment.items():
        monkeypatch.setenv(key, value)
    monkeypatch.delenv("GC_RIG", raising=False)
    monkeypatch.chdir(workdir)

    assert module.validate_worker_boundary() == "mayor"
    monkeypatch.setenv("GC_WORKER_BOUNDARY_ROLE", "hq")
    with pytest.raises(RuntimeError, match="did not receive the Mayor boundary"):
        module.validate_worker_boundary()


def test_static_topology_keeps_hq_private_and_scopes_mayor_material() -> None:
    compose = (DEPLOY / "compose.yaml").read_text(encoding="utf-8")
    launcher = (DEPLOY / "bin/provider-container").read_text(encoding="utf-8")
    dockerfile = (DEPLOY / "docker/Dockerfile").read_text(encoding="utf-8")
    supervisor = SUPERVISOR.read_text(encoding="utf-8")

    assert "aegis-control\n      - hq-control" in compose
    assert "hq-dolt:" in compose and "networks:\n      - hq-control" in compose
    assert '"$boundary_helper" "${boundary_args[@]}"' in launcher
    assert "partial or conflicting trusted Mayor identity" in launcher
    assert "dst=/run/secrets/aegis_beads_password,readonly" in launcher
    assert "dst=$aegis_beads_dir,readonly" in launcher
    assert "dst=$aegis_beads_dir/metadata.json,readonly" in launcher
    assert "BEADS_CREDENTIALS_FILE=/home/worker/.config/beads/credentials" in launcher
    assert "--env GC_DOLT_PASSWORD_FILE" not in launcher
    assert "--env BEADS_DOLT_PASSWORD_FILE" not in launcher
    assert "COPY config/city.worker.toml /opt/gas-city/city.worker.toml" in dockerfile
    worker_digest = hashlib.sha256((DEPLOY / "config/city.worker.toml").read_bytes()).hexdigest()
    assert worker_digest in dockerfile
    assert 'os.environ["GC_DOLT_PASSWORD"]' not in supervisor
    assert 'os.environ["BEADS_DOLT_PASSWORD"]' not in supervisor
    assert "prepare_dolt_credentials(boundary_role)" in supervisor


def test_pinned_gc_projects_aegis_endpoint_and_user_without_hq_contamination(
    tmp_path: Path,
) -> None:
    """Exercise real v1.3.5 `gc bd --rig` and `gc sling` against a fake bd."""

    city = _private(tmp_path / "city")
    rig = _private(tmp_path / "aegis")
    city_beads = _private(city / ".beads")
    rig_beads = _private(rig / ".beads")
    gc_state = _private(city / ".gc")
    # Use the exact production worker config and lock surface.  HOME is an
    # isolated writable tmpfs analogue below, so the pinned binary must resolve
    # its bundled pack cache without reading the operator's shared ~/.gc state.
    shutil.copyfile(DEPLOY / "config/city.worker.toml", city / "city.toml")
    shutil.copyfile(DEPLOY / "config/pack.toml", city / "pack.toml")
    shutil.copyfile(DEPLOY / "config/packs.lock", city / "packs.lock")
    for path in (city / "city.toml", city / "pack.toml", city / "packs.lock"):
        path.chmod(0o600)
    _write(city_beads / "config.yaml", _load_supervisor().HQ_CONFIG_OVERLAY_CONTENT)
    _write(
        city_beads / "metadata.json",
        json.dumps(
            {
                "backend": "dolt",
                "database": "dolt",
                "dolt_database": "hq",
                "dolt_mode": "server",
                "project_id": "254f7a68-e7d1-4c9f-997b-e879cb1b8dd1",
            },
            sort_keys=True,
        )
        + "\n",
    )
    supervisor = _load_supervisor()
    _write(rig_beads / "config.yaml", supervisor.AEGIS_CONFIG_OVERLAY_CONTENT)
    _write(
        rig_beads / "metadata.json",
        json.dumps(
            {
                "backend": "dolt",
                "database": "dolt",
                "dolt_database": "aegis_beads",
                "dolt_mode": "server",
                "dolt_server_host": "gas-city-aegis-dolt",
                "dolt_server_port": 3306,
                "dolt_server_user": "aegis_beads",
                "project_id": "74eb5b48-1390-4fc8-a88d-2b979bcfa7b5",
            },
            sort_keys=True,
        )
        + "\n",
    )
    _write(
        gc_state / "site.toml",
        f'workspace_name = "gas-city"\n[[rig]]\nname = "aegis"\npath = "{rig}"\n',
    )
    fake_bin = _private(tmp_path / "bin")
    fake_home = _private(tmp_path / "home")
    observed = tmp_path / "bd-env.json"
    fake_bd = _write(
        fake_bin / "bd",
        "#!/usr/bin/env python3\n"
        "import json, os, pathlib, sys\n"
        "keys = ['GC_DOLT_HOST','GC_DOLT_PORT','GC_DOLT_USER',"
        "'GC_DOLT_DATABASE',"
        "'BEADS_DOLT_SERVER_HOST','BEADS_DOLT_SERVER_PORT',"
        "'BEADS_DOLT_SERVER_USER','BEADS_DOLT_SERVER_DATABASE',"
        "'BEADS_DIR','BEADS_CREDENTIALS_FILE']\n"
        "pathlib.Path(os.environ['FAKE_BD_ENV']).write_text("
        "json.dumps({key: os.environ.get(key) for key in keys}), encoding='utf-8')\n"
        "if 'show' in sys.argv:\n"
        "    print('[]')\n",
        0o700,
    )
    assert fake_bd.is_file()
    credentials = _write(
        tmp_path / "credentials",
        "[gas-city-hq-dolt:3306]\npassword=" + "H" * 40 + "\n"
        "[gas-city-aegis-dolt:3306]\npassword=" + "A" * 40 + "\n",
    )
    environment = {
        **os.environ,
        "PATH": f"{fake_bin}:/usr/bin:/bin",
        "HOME": str(fake_home),
        "GC_CITY": str(city),
        "GC_CITY_ROOT": str(city),
        "FAKE_BD_ENV": str(observed),
        "BEADS_CREDENTIALS_FILE": str(credentials),
        # The primary direct-bd mirror may remain; GC must replace it for the
        # selected rig. User/database mirrors are intentionally absent after
        # supervisor because v1.3.5 does not safely scope all of them.
        "BEADS_DOLT_SERVER_USER": "gas_city_hq",
        "GC_DOLT_DATABASE": "hq",
        "BEADS_DOLT_SERVER_DATABASE": "hq",
    }
    for name in (
        "GC_DOLT_USER",
        "GC_DOLT_DATABASE",
        "GC_DOLT_PASSWORD",
        "BEADS_DOLT_PASSWORD",
        "BEADS_DOLT_SERVER_DATABASE",
    ):
        environment.pop(name, None)
    hq = subprocess.run(
        [str(DEPLOY / "artifacts/gc"), "bd", "list"],
        cwd=city,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )
    assert hq.returncode == 0, hq.stderr
    assert json.loads(observed.read_text(encoding="utf-8")) == {
        "GC_DOLT_HOST": "gas-city-hq-dolt",
        "GC_DOLT_PORT": "3306",
        "GC_DOLT_USER": "gas_city_hq",
        "GC_DOLT_DATABASE": None,
        "BEADS_DOLT_SERVER_HOST": "gas-city-hq-dolt",
        "BEADS_DOLT_SERVER_PORT": "3306",
        "BEADS_DOLT_SERVER_USER": "gas_city_hq",
        "BEADS_DOLT_SERVER_DATABASE": None,
        "BEADS_DIR": str(city_beads),
        "BEADS_CREDENTIALS_FILE": str(credentials),
    }
    result = subprocess.run(
        [str(DEPLOY / "artifacts/gc"), "bd", "--rig", "aegis", "list"],
        cwd=city,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    projected = json.loads(observed.read_text(encoding="utf-8"))
    assert projected == {
        "GC_DOLT_HOST": "gas-city-aegis-dolt",
        "GC_DOLT_PORT": "3306",
        "GC_DOLT_USER": "aegis_beads",
        "GC_DOLT_DATABASE": None,
        "BEADS_DOLT_SERVER_HOST": "gas-city-aegis-dolt",
        "BEADS_DOLT_SERVER_PORT": "3306",
        "BEADS_DOLT_SERVER_USER": "aegis_beads",
        "BEADS_DOLT_SERVER_DATABASE": None,
        "BEADS_DIR": str(rig_beads),
        "BEADS_CREDENTIALS_FILE": str(credentials),
    }

    sling = subprocess.run(
        [
            str(DEPLOY / "artifacts/gc"),
            "sling",
            "aegis/gastown.polecat",
            "cross-rig preview",
            "--dry-run",
            "--no-formula",
            "--no-convoy",
        ],
        cwd=city,
        env=environment,
        text=True,
        capture_output=True,
        check=False,
    )
    assert sling.returncode == 0, sling.stderr
    assert "aegis/gastown.polecat" in sling.stdout
    assert "No side effects executed (--dry-run)." in sling.stdout
    assert json.loads(observed.read_text(encoding="utf-8")) == projected
