Port 8888
Listen 0.0.0.0
Timeout 600
MaxClients 32

Allow 0.0.0.0/0
Filter "/etc/tinyproxy/filter"
FilterType ere
FilterURLs No
FilterCaseSensitive No
FilterDefaultDeny Yes
ConnectPort 443

LogLevel Connect
PidFile "/tmp/tinyproxy.pid"
DisableViaHeader Yes
